### ISSUE TITLE
Problem with LimitPercent 

### ISSUE THREAD

**Issue by mvalletta** [derFunk/monit-windows-agent#10]
Hi
the percent of free space for a FS, is always 0.
This is due to a wrong percent calculation.
In FilesystemHelper.cs at line 32 there is the following code:

space_percent = Convert.ToInt16((sc.TotalSize == 0) ? 10 : ((sc.TotalFreeSpace/sc.TotalSize)*10))

Because variable are long and the sc.TotalFreeSpace/sc.TotalSize return always a number between 0 and 1 it will be truncated to 0.

I tried the the following code that works:

space_percent = Convert.ToInt16((sc.TotalSize == 0) ? 0 : ((sc.TotalFreeSpace \* 100 / sc.TotalSize)));

First multiply by 100 TotalFreeSpace and after divide it by TotalSize.

I had also modified the following code in Validate.cs, line 1426, to correctly display the event in mmonit:

Event.Post(s, MonitEventType.Event_Resource, MonitStateType.State_Failed, td.action, "space usage {0}% matches resource limit [space usage{1}{2}%]", filesystem.space_percent/10f, td.compOperator, td.limit_percent/10f);

I deleted divide by 10f

**Comment by m4x1202** [comment]
Thanks for opening this issue.
It has been fixed in the latest push.
Since the original monit code has changed in this regard aswell, the changes that you proposed are now obsolete and fixed

**Comment by mvalletta** [comment]
Perfect!
Thanks
