### ISSUE TITLE
LimitAbsolute ignored

### ISSUE THREAD

**Issue by mvalletta** [derFunk/monit-windows-agent#11]
Hi

LimiteAbsolute attribute in Filesystem tag is ignored.

Line 1394 to 1398 in Event.cs
            if ((td.limit_percent < 0) && (td.limit_absolute < 0))
            {
                Logger.Log.ErrorFormat("'{0}' error: filesystem limit not set", s.name);
                return;
            }
force to insert both LimitPercent and LimitAbosolute so at line 1424 the condition
    if (td.limit_percent >= 0) {
is always true and LimitAbsolute is ignored.

**Comment by m4x1202** [comment]
Thank you for opening this issue.
It has been fixed in the latest push.

**Comment by mvalletta** [comment]
Perfect!
Thanks
