### ISSUE TITLE
Services which contain spaces not showing in MMonit

### ISSUE THREAD

**Issue by asulik1988** [derFunk/monit-windows-agent#13]
If the service I'm trying to monitor does not have a space, it works great and shows up in mMonit. But if there's a space, then no luck. Web client shows, but not bluetooth device monitor. I've tried double sets of double quotes, just one set of double quotes, throwing single quotes in there, all no bueno.
`
<Services>
    <Process Name=""bluetooth device monitor"">
      <ActionRate Count="3" Cycle="5" ActionType="5"></ActionRate>
      <Resources>
        <Resource Type="1" ComparisonOperator=">" Limit="800" ActionType="2" />
      </Resources>
    </Process>
    <Process Name="webclient">
      <ActionRate Count="3" Cycle="5" ActionType="5"></ActionRate>
      <Resources>
        <Resource Type="1" ComparisonOperator=">" Limit="800" ActionType="2" />
      </Resources>
    </Process>
    <Filesystem Name="C:\"></Filesystem>
  </Services>
`

**Comment by m4x1202** [comment]
Hey,
thanks for your issue.

![Hyper-V Windows Service](https://cloud.githubusercontent.com/assets/6067433/22885106/32ea6410-f1f8-11e6-9684-0d182e8b4fd8.png)


As you can see in the image above the 'Service name' of a Windows-Service never includes whitespaces.
Therefore can you try to use the 'Service name' of the "bluetooth device monitor"-Service you are trying to monitor.
If this still does not work please leave me another comment.

Thx

**Comment by asulik1988** [comment]
Thanks for the super quick response. And while true is most cases, there can be service names with spaces. As shown in the attached picture. (FYI great job on this by the way, It's working fantastically for what I'm playing with !!)

![winservice](https://cloud.githubusercontent.com/assets/7950718/22898556/b9cd805a-f1f5-11e6-83ea-f711bcc5797c.JPG)

**Comment by m4x1202** [comment]
Hey,

sry this response took a little longer.
I did a new [release ](https://github.com/ChimeraEntertainment/monit-windows-agent/releases/tag/v0.1.12), using which i was able to add Services with Whitespaces in them.
![image](https://cloud.githubusercontent.com/assets/6067433/23063481/1581a1de-f50b-11e6-9a83-00eee306501c.png)

Thanks for your kind words, I hope your issue is resolved in this new version.
If not, please leave another comment.
