### ISSUE TITLE
Services monitoring

### ISSUE THREAD

**Issue by marcelomagf** [derFunk/monit-windows-agent#5]
Managed to get it running and sending reports to my mmonit. Nice! Not sure about services monitoring thou. Is it suposed to monitor windows services and report it to mmonit?

**Comment by nickjwebb** [comment]
Sorry to add a non meaty response here, but if this is working for windows processes, even if it needs a bit of love, we would be thrilled. May be able to put some resources on it, too, if it needs polishing.

**Comment by RickyBost42** [comment]
Hi Guys, 

I'm new with this. can you help me make this work?. current Problem i have is that i don't know why there's no  MonitorWinowsAgent.exe being created or Do i need to create that?. can you give me intructions on how to make it work?. 

I would appreciate if you respond. 

Thank you.

**Comment by m4x1202** [comment]
@RickyBost42  you will have to build the project using e.g. MS VS. The '.exe' file will then be created in /bin/Debug|Release/

**Comment by m4x1202** [comment]
- Service reporting is working in the newest version
