### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by seanvree** [derFunk/monit-windows-agent#6]
I don't get it? How do we install on a windows box?  I guess you're using C#, but I don't understand how to actually install the service?

**Comment by RickyBost42** [comment]
You need to do the service, Re-configure most in C# and create Service file for it

**Comment by m4x1202** [comment]
This has been resolved with the new version. The only thing you will have to provide is a proper configuration xml-file.

**Comment by RickyBost42** [comment]
hi, im not good at using C#, and didn't understand when u said we need to provide a proper configuration xml-file. can u give us step-by-step action on how to install this?

**Comment by m4x1202** [comment]
Hey @RickyBost42 to install the service you will only need to grab the release of the Monit-Windows-Agent (https://github.com/ChimeraEntertainment/monit-windows-agent/releases/download/v0.1.11/monit-windows-agent.zip) and execute the commands provided in the README: https://github.com/ChimeraEntertainment/monit-windows-agent#install

The configuration xml replaces the monitrc configuration of the usual Monit. A sample configuration will be put into your installation directory (<install-dir/MonitWindowsAgentConfig.xml). There you will have to define what services and filesystems Monit should monitor and where your M/Monit server is located.

For Example:

``` xml
<Process Name="AdobeARMservice">
  <ActionRate Count="3" Cycle="5" ActionType="5"></ActionRate>
  <Resources>
    <Resource Type="1" ComparisonOperator=">" Limit="800" ActionType="2" />
  </Resources>
</Process>
```

This would be the configuration to monitor the Adobe Update Service.

**Comment by RickyBost42** [comment]
Thank you, This helped me a lot
