### ISSUE TITLE
Problem with monit config on windows

### ISSUE THREAD

**Issue by makvack** [derFunk/monit-windows-agent#7]
Hi,

I have just installed this and it is working. The problem is that there is no examplefiles working and nothing else that can be used by someone wanting to try this out. Can you help me with some example configfiles that is actually working?

**Comment by makvack** [comment]
I take that back, it doesnt report any data.

**Comment by RickyBost42** [comment]
I still developing it. I will give you the update once im done.

**Comment by makvack** [comment]
Alright , good to hear!

With kind regards / Marcus

25 apr. 2016 kl. 14:56 skrev RickyBost42 <notifications@github.com<mailto:notifications@github.com>>:

I still developing it. I will give you the update once im done.

On Mon, Apr 25, 2016 at 8:47 PM, makvack <notifications@github.com<mailto:notifications@github.com>> wrote:

> I take that back, it doesnt report any data.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/derFunk/monit-windows-agent/issues/7#issuecomment-214300224

##

**Comment by m4x1202** [comment]
- Since the newest update the reporting should be fixed.
- On first run a default config file will now be created.
